[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "music-rag-recommender"
author = "Ela Murgelj"
version = "0.1.0"
description = "Cold-start music recommendation using RAG and NLP"
licence = {text = "MIT" }
readme = "README.md"
keywords = [
    "RAG", 
    "sentence-transformers", 
    "music recommendation engine", 
    "cold-start problem",
    "faiss",
    "large language models"
]
dependencies = "requirements.txt"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Repository = "https://github.com/elamurg/music-rag-recommender"
Documentation = "https://github.com/elamurg/music-rag-recommender/blob/main/README.md"

